apiVersion: v1
data:
  conf.json: '{"processes": 2, "logging": true, "protocol": "http", "endpoints": [{"name":
    "endpoint1", "execution_mode": "parallel", "cpu_complexity": {"execution_time":
    0.03125, "threads": 1}, "network_complexity": {"forward_requests": "asynchronous",
    "response_payload_size": 100, "called_services": null}}]}'
kind: ConfigMap
metadata:
  labels:
    name: config-ms8-1-3
    version: cluster-1
  name: config-ms8-1-3
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: cluster-1
  name: ms8-1-3
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ms8-1-3
      version: cluster-1
  template:
    metadata:
      annotations: {}
      labels:
        app: ms8-1-3
        version: cluster-1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: ms8-1-3
        - name: GOMEMLIMIT
          value: '100000000'
        - name: CPU_REQUEST
          value: '100'
        image: rexyyj/hydragen-emulator:e9fe0194
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 100M
          requests:
            cpu: 100m
            memory: 50M
        volumeMounts:
        - mountPath: /usr/src/emulator/config
          name: config-data-volume
      nodeName: dummy
      volumes:
      - configMap:
          name: config-ms8-1-3
        name: config-data-volume
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    http: /
  labels:
    version: cluster-1
  name: ms8-1-3
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: ms8-1-3
