apiVersion: v1
data:
  conf.json: '{"processes": 2, "logging": true, "protocol": "http", "endpoints": [{"name":
    "endpoint1", "execution_mode": "parallel", "cpu_complexity": {"execution_time":
    0.1, "threads": 1}, "network_complexity": {"forward_requests": "asynchronous",
    "response_payload_size": 512, "called_services": null}}]}'
kind: ConfigMap
metadata:
  labels:
    name: config-service2-2-1
    version: cluster-1
  name: config-service2-2-1
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: cluster-1
  name: service2-2-1
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: service2-2-1
      version: cluster-1
  template:
    metadata:
      annotations: {}
      labels:
        app: service2-2-1
        version: cluster-1
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: service2-2-1
        - name: GOMEMLIMIT
          value: '1024000000'
        - name: CPU_REQUEST
          value: '10'
        image: rexyyj/hydragen-emulator:442111c0
        imagePullPolicy: Never
        name: app
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
          requests:
            cpu: 1000m
            memory: 1024M
        volumeMounts:
        - mountPath: /usr/src/emulator/config
          name: config-data-volume
      nodeName: dummy
      volumes:
      - configMap:
          name: config-service2-2-1
        name: config-data-volume
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    http: /
  labels:
    version: cluster-1
  name: service2-2-1
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: service2-2-1
