apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service1
    labels:
        name: config-service1
        version: cluster-1
    namespace: default
data:
    conf.json: '{"processes":2,"logging":true,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":0.05,"threads":1},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":512,"called_services":[{"service":"service2","port":80,"endpoint":"endpoint1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":256}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service1
    namespace: default
    labels:
        version: cluster-1
spec:
    selector:
        matchLabels:
            app: service1
            version: cluster-1
    replicas: 1
    template:
        metadata:
            labels:
                app: service1
                version: cluster-1
            annotations: {}
        spec:
            nodeName: k8s-node
            containers:
                - name: app
                  image: rexyyj/hydragen-emulator:442111c0
                  imagePullPolicy: Never
                  env:
                    - name: SERVICE_NAME
                      value: service1
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 1
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 1000m
                        memory: 1024M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service1
---
apiVersion: v1
kind: Service
metadata:
    name: service1
    namespace: default
    labels:
        version: cluster-1
    annotations:
        http: /
spec:
    selector:
        app: service1
    ports:
        - name: http
          port: 80
          targetPort: 5000
